# Generated by Django 5.2.11 on 2026-02-23 16:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Filiale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Filiali",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "dipendente"),
                            (2, "responsabile"),
                            (3, "super"),
                            (4, "up"),
                            (5, "responsabile_cons"),
                            (6, "test"),
                            (7, "amministrazione"),
                        ],
                        default=1,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dipendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=200)),
                ("cognome", models.CharField(max_length=200)),
                ("inizio_val", models.DateField()),
                ("fine_val", models.DateField()),
                ("mansione", models.CharField(blank=True, max_length=200)),
                ("cat", models.CharField(default="A", max_length=1)),
                ("chiamata", models.BooleanField(default=False)),
                (
                    "filiale",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.filiale",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Dipendenti",
                "ordering": ("cognome",),
            },
        ),
        migrations.CreateModel(
            name="Comunicazione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("testo", models.TextField()),
                (
                    "filiale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.filiale"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comunicazioni",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, max_length=40, unique=True, verbose_name="Key"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cf",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(16)],
                    ),
                ),
                ("roles", models.ManyToManyField(to="app.role")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="utente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Responsabile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filiale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.filiale"
                    ),
                ),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Responsabili",
            },
        ),
        migrations.CreateModel(
            name="ActionLogs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("azione", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField()),
                (
                    "utente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.userprofile",
                        verbose_name="Utente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comune", models.CharField(max_length=200)),
                ("zona", models.CharField(max_length=200)),
                ("soglia", models.PositiveSmallIntegerField()),
                ("valore", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "filiale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.filiale"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Zone",
            },
        ),
        migrations.CreateModel(
            name="ZonaNuova",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveSmallIntegerField()),
                ("comune", models.CharField(blank=True, max_length=200)),
                ("zona", models.CharField(max_length=200)),
                ("soglia", models.PositiveSmallIntegerField()),
                ("valore", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "filiale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.filiale"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ZoneNuove",
            },
        ),
        migrations.CreateModel(
            name="Consegne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("effettuate", models.PositiveIntegerField(default=0)),
                ("assegnate", models.PositiveIntegerField(default=0)),
                ("ritiri", models.PositiveIntegerField(default=0)),
                (
                    "dipendente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consegne",
                        to="app.dipendente",
                    ),
                ),
                (
                    "filiale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.filiale"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Consegne",
                "unique_together": {("dipendente", "data")},
            },
        ),
        migrations.CreateModel(
            name="Presenza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                (
                    "presenza",
                    models.CharField(
                        choices=[
                            ("si", "PRESENTE"),
                            ("mez", "MEZZA GIORNATA"),
                            ("no", "NO"),
                            ("fer", "FERIE"),
                            ("mal", "MAL"),
                            ("inf", "INF"),
                            ("104", "104"),
                            ("mat", "MATTINA"),
                            ("int", "INTERA GIORNATA"),
                            ("sin", "PERMESSO SINDAC"),
                        ],
                        default="si",
                        max_length=3,
                    ),
                ),
                ("zona", models.PositiveIntegerField()),
                ("macrozona", models.CharField(blank=True, default="", max_length=2)),
                (
                    "straordinari",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("caricato", models.BooleanField(default=False)),
                ("servizi_straordinari", models.BooleanField(default=False)),
                ("esenzione", models.BooleanField(default=False)),
                ("affiancamento", models.BooleanField(default=False)),
                (
                    "annotazioni",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "dipendente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presenze",
                        to="app.dipendente",
                    ),
                ),
                (
                    "filiale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.filiale"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Presenze",
                "unique_together": {("dipendente", "data")},
            },
        ),
    ]
